name: dmrs
channels:
  - conda-forge
  - bioconda
  - defaults
dependencies:
  - _libgcc_mutex=0.1
  - _openmp_mutex=4.5
  - _r-mutex=1.0.1
  - bedtools=2.29.2
  - binutils_impl_linux-64=2.34
  - binutils_linux-64=2.34
  - bwidget=1.9.14
  - bzip2=1.0.8
  - c-ares=1.16.1
  - ca-certificates=2020.6.20
  - cairo=1.16.0
  - certifi=2020.6.20
  - curl=7.71.1
  - expat=2.2.9
  - fontconfig=2.13.1
  - freetype=2.10.2
  - fribidi=1.0.10
  - gcc_impl_linux-64=7.5.0
  - gcc_linux-64=7.5.0
  - gettext=0.19.8.1
  - gfortran_impl_linux-64=7.5.0
  - gfortran_linux-64=7.5.0
  - glib=2.58.3
  - graphite2=1.3.13
  - graphviz=2.42.3
  - gsl=2.6
  - gxx_impl_linux-64=7.5.0
  - gxx_linux-64=7.5.0
  - harfbuzz=2.7.2
  - icu=67.1
  - jpeg=9d
  - krb5=1.17.1
  - ld_impl_linux-64=2.34
  - libblas=3.8.0
  - libcblas=3.8.0
  - libcurl=7.71.1
  - libedit=3.1.20191231
  - libev=4.33
  - libffi=3.2.1
  - libgcc-ng=9.3.0
  - libgfortran-ng=7.5.0
  - libgomp=9.3.0
  - libiconv=1.16
  - liblapack=3.8.0
  - libnghttp2=1.41.0
  - libopenblas=0.3.10
  - libpng=1.6.37
  - libssh2=1.9.0
  - libstdcxx-ng=9.3.0
  - libtiff=4.1.0
  - libtool=2.4.6
  - libuuid=2.32.1
  - libwebp-base=1.1.0
  - libxcb=1.13
  - libxml2=2.9.10
  - lz4-c=1.9.2
  - make=4.3
  - metilene=0.2.8
  - ncurses=6.2
  - openssl=1.1.1g
  - pango=1.42.4
  - pcre=8.44
  - pcre2=10.35
  - perl=5.30.3
  - pip=20.2.2
  - pixman=0.38.0
  - pthread-stubs=0.4
  - python=3.8.5
  - python_abi=3.8
  - r-assertthat=0.2.1
  - r-backports=1.1.9
  - r-base=4.0.2
  - r-bitops=1.0_6
  - r-callr=3.4.3
  - r-catools=1.18.0
  - r-cli=2.0.2
  - r-colorspace=1.4_1
  - r-crayon=1.3.4
  - r-desc=1.2.0
  - r-digest=0.6.25
  - r-ellipsis=0.3.1
  - r-evaluate=0.14
  - r-fansi=0.4.1
  - r-farver=2.0.3
  - r-gdata=2.18.0
  - r-ggplot2=3.3.2
  - r-glue=1.4.2
  - r-gplots=3.0.4
  - r-gtable=0.3.0
  - r-gtools=3.8.2
  - r-isoband=0.2.2
  - r-kernsmooth=2.23_17
  - r-labeling=0.3
  - r-lattice=0.20_41
  - r-lifecycle=0.2.0
  - r-magrittr=1.5
  - r-mass=7.3_52
  - r-matrix=1.2_18
  - r-mgcv=1.8_33
  - r-munsell=0.5.0
  - r-nlme=3.1_149
  - r-pillar=1.4.6
  - r-pkgbuild=1.1.0
  - r-pkgconfig=2.0.3
  - r-pkgload=1.1.0
  - r-praise=1.0.0
  - r-prettyunits=1.1.1
  - r-processx=3.4.3
  - r-ps=1.3.4
  - r-r6=2.4.1
  - r-rcolorbrewer=1.1_2
  - r-rcpp=1.0.4.6
  - r-rlang=0.4.7
  - r-rprojroot=1.3_2
  - r-rstudioapi=0.11
  - r-scales=1.1.1
  - r-testthat=2.3.2
  - r-tibble=3.0.3
  - r-utf8=1.1.4
  - r-vctrs=0.3.4
  - r-viridislite=0.3.0
  - r-withr=2.2.0
  - r-zeallot=0.1.0
  - readline=8.0
  - sed=4.8
  - setuptools=49.6.0
  - sqlite=3.33.0
  - tk=8.6.10
  - tktable=2.10
  - wheel=0.35.1
  - xorg-kbproto=1.0.7
  - xorg-libice=1.0.10
  - xorg-libsm=1.2.3
  - xorg-libx11=1.6.12
  - xorg-libxau=1.0.9
  - xorg-libxdmcp=1.1.3
  - xorg-libxext=1.3.4
  - xorg-libxpm=3.5.13
  - xorg-libxrender=0.9.10
  - xorg-libxt=1.1.5
  - xorg-renderproto=0.11.1
  - xorg-xextproto=7.3.0
  - xorg-xproto=7.0.31
  - xz=5.2.5
  - zlib=1.2.11
  - zstd=1.4.5
